/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CORE;

import la_red.USUARIO;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author SAMSUNG
 */
public class USUARIOS_PANEL extends javax.swing.JPanel implements Runnable {
    private USUARIO selectedUser;
    /**
     * Creates new form USUARIOS_PANEL
     */
    public USUARIOS_PANEL(String endpoint) {
        initComponents();
         JSONArray usuarios = (JSONArray)BE.read(endpoint, LA_RED.usuario.toJSON());
        System.out.println(usuarios);
//        DefaultListModel lista = new DefaultListModel();
        for (Object usuario : usuarios) {
            int pos = usuarios.indexOf(usuario);
            USUARIO nUsuario = new USUARIO( (JSONObject)usuario , this);
            if( usuarios.indexOf(usuario) == 0 ){
                selectedUser = nUsuario;
            }
            
//            lista.addElement( nUsuario );
            VISTA_USER_SMALL vistaSmall = nUsuario.getVistaSmall();
            vistaSmall.btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    getUser( evt, nUsuario );
                }
            });
            if( endpoint.equals("listarUsuarios") ){
                int solicitado = Integer.parseInt( ((JSONObject)usuario ).get("solicitado").toString() );
                int enviada = Integer.parseInt( ((JSONObject)usuario ).get("enviada").toString() );
                if( solicitado == 1){
                    vistaSmall.btnSolicitud.setText("Aceptar Solicitud");
                }
                if( enviada == 1){
                   vistaSmall.btnSolicitud.setText("Cancelar Solicitud");
                }
                if( solicitado != 1 && enviada != 1 ){
                    vistaSmall.btnSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            JSONObject data = new JSONObject();
                            data.put("id", selectedUser.getId());
                            BE.read("enviarSolicitud", data);
                        }
                    });
                }
            }else if( endpoint.equals("listarSolicitudes")){
                vistaSmall.btnSolicitud.setText("Aceptar Solicitud");
                vistaSmall.btnSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        JSONObject data = new JSONObject();
                        data.put("id", selectedUser.getId());
                        BE.read("aceptarSolicitud", data);
                    }
                });
            }else if( endpoint.equals("listarAmigos")){
                vistaSmall.btnSolicitud.setText("Eliminar Amigo");
                vistaSmall.btnSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        JSONObject data = new JSONObject();
                        data.put("id", selectedUser.getId());
                        BE.read("eliminarAmigo", data);
                    }
                });
                
            }
            vistaSmall.setBounds(0, pos * 80, 200, 80);
            vistaSmall.setVisible(true);
            this.add( vistaSmall );
        }
        repaint();
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void getUser(java.awt.event.MouseEvent evt, USUARIO nUsuario){
        System.out.println("Id ===> " + nUsuario.getId());
        selectedUser = nUsuario;
    }

    public USUARIO getSelectedUser() {
        return selectedUser;
    }
    
    public void run(){
        while( true ){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
