/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRIENDLY;

import CORE.BE;
import CORE.USUARIOS_PANEL;
import static java.lang.Integer.parseInt;
import la_red.LA_RED;
import la_red.USUARIO;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author SAMSUNG
 */
public class MENSAJERIA extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MENSAJERIA
     */
    private boolean esNotificacion;
    private Thread proceso;
    public MENSAJERIA() {
        initComponents();
    }
    public MENSAJERIA(boolean esNotificacion) {
        initComponents();
        this.cmbUrgencia.setVisible(esNotificacion);
        this.esNotificacion = esNotificacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensajes = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jpUsuarios = new javax.swing.JPanel();
        txtAsunto = new javax.swing.JTextField();
        cmbUrgencia = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        txtMensajes.setEnabled(false);
        jScrollPane2.setViewportView(txtMensajes);

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        jScrollPane3.setViewportView(txtMensaje);

        jButton1.setText("Enviar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpUsuariosLayout = new javax.swing.GroupLayout(jpUsuarios);
        jpUsuarios.setLayout(jpUsuariosLayout);
        jpUsuariosLayout.setHorizontalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );
        jpUsuariosLayout.setVerticalGroup(
            jpUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jpUsuarios);

        cmbUrgencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baja", "Media", "Alta", "Catastrofica" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(cmbUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbUrgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
//         JSONArray usuarios = (JSONArray)BE.read("listarUsuarios", LA_RED.usuario.toJSON());
//        System.out.println(usuarios);
//        for (Object usuario : usuarios) {
//            int pos = usuarios.indexOf(usuario);
//            USUARIO nUsuario = new USUARIO( (JSONObject)usuario, this );
            vistaSmall = new USUARIOS_PANEL( "listarAmigos" );
            
            vistaSmall.setBounds(0, 0, 200, 500);
            vistaSmall.setVisible(true);
            this.jpUsuarios.add( vistaSmall );
//        }
        jpUsuarios.repaint();
        jpUsuarios.validate();
        selectedUser = vistaSmall.getSelectedUser();
        proceso =  new Thread( this );
        
        proceso.start();
    }//GEN-LAST:event_formComponentShown

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JSONObject data = new JSONObject( );
        data.put("id_amigo", selectedUser.getId() );
        data.put("asunto", txtAsunto.getText() );
        data.put("contexto", txtMensaje.getText() );
        if( esNotificacion ){
            data.put("urgencia", this.cmbUrgencia.getSelectedItem().toString());
        }
        BE.read("enviarMensaje", data);
    }//GEN-LAST:event_jButton1MouseClicked

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        proceso.stop();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENSAJERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENSAJERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENSAJERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENSAJERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENSAJERIA().setVisible(true);
            }
        });
    }
    public void run(){
        while( true ){
            try {
//                System.out.println(selectedUser.getId() + " !== " + vistaSmall.getSelectedUser().getId() );
//                if( selectedUser.getId() != vistaSmall.getSelectedUser().getId() ){
                    selectedUser = vistaSmall.getSelectedUser();
                    JSONObject data = new JSONObject();
                    data.put("id_amigo",selectedUser.getId());
                    data.put("tipo", esNotificacion ? "notificacion" : "mensaje");
                    JSONArray mensajes = (JSONArray)BE.read("obtenerMsj", data);
                    String contenido = "";
                    for (Object mensaje : mensajes) {
                        int pos = mensajes.indexOf(mensaje) * 120;
                        JSONObject msjJSON = (JSONObject)mensaje;
                        String nombre = "";
                        if( selectedUser.getId() == parseInt(msjJSON.get("id_remitente").toString() ) ){
                            nombre = selectedUser.getUser_name();
                        }else{
                            nombre = LA_RED.usuario.getUser_name();
                        }
//                        MENSAJE nMensaje = new MENSAJE( nombre,msjJSON.get("asunto").toString(),msjJSON.get("contexto").toString());
//                        nMensaje.setSize(400,120);
//                        nMensaje.setVisible(true);
                        
                        contenido += msjJSON.get("fecha") + " "+ nombre + "--> ( " + msjJSON.get("asunto") + ") ";
                        if( esNotificacion ){
                            contenido += "URGENCIA -- > " + msjJSON.get("urgencia") + " ";
                        }
                        contenido += msjJSON.get("contexto") + ( msjJSON.get("leido").toString().equals("true") ? "" :" NO") + " VISTO" +"\n";
                    }
                    
                      
                    txtMensajes.setText( contenido );
//                    Thread.sleep( 1000 );
                    System.out.println("Mensajes ===> " + mensajes.toJSONString());
                    System.out.println( "SELECTED =============> " + selectedUser.getId() );
//                }
                Thread.sleep( 1000 );
            } catch (Exception e) {
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbUrgencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpUsuarios;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextArea txtMensaje;
    private javax.swing.JTextPane txtMensajes;
    // End of variables declaration//GEN-END:variables
    private USUARIO selectedUser;
    private USUARIOS_PANEL vistaSmall;
}
